<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\NormaKerja;

class NormaKerjaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'CW - Manual',
                'datar_norma' => 1.8,
                'datar_rotasi' => 1,
                'datar_nxr' => 1.8,
                'roling1_norma' => 2,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 2,
                'roling2_norma' => 2.2,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 2.2,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'CW - Chemist',
                'datar_norma' => 0.35,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.0499999999999998,
                'roling1_norma' => 0.35,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 1.0499999999999998,
                'roling2_norma' => 0.35,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 1.0499999999999998,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Rawat Path - Chemist',
                'datar_norma' => 0.0675,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.27,
                'roling1_norma' => 0.075,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.3,
                'roling2_norma' => 0.0825,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.33,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Rawat TPH - Chemist',
                'datar_norma' => 0.06213275762092268,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.2485310304836907,
                'roling1_norma' => 0.06834603338301495,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.2733841335320598,
                'roling2_norma' => 0.07455930914510721,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.29823723658042883,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Weeding (Dak) - Manual',
                'datar_norma' => 1.35,
                'datar_rotasi' => 1,
                'datar_nxr' => 1.35,
                'roling1_norma' => 1.45,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 1.45,
                'roling2_norma' => 1.6,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 1.6,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Weeding - Chemist',
                'datar_norma' => 0.45,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.35,
                'roling1_norma' => 0.45,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 1.35,
                'roling2_norma' => 0.45,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 1.35,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Wipping Lalang',
                'datar_norma' => 0.09000000000000001,
                'datar_rotasi' => 6,
                'datar_nxr' => 0.54,
                'roling1_norma' => 0.09900000000000002,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 0.5940000000000001,
                'roling2_norma' => 0.10800000000000001,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 0.6480000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Rawat/Cuci Flatbat',
                'datar_norma' => 0.20700000000000002,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.41400000000000003,
                'roling1_norma' => 0.22770000000000004,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.4554000000000001,
                'roling2_norma' => 0.2484,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.4968,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Pengaliran Land Aplikasi',
                'datar_norma' => 0.63,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.8900000000000001,
                'roling1_norma' => 0.6930000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 2.079,
                'roling2_norma' => 0.756,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 2.268,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Pruning',
                'datar_norma' => 0.4,
                'datar_rotasi' => 12,
                'datar_nxr' => 4.800000000000001,
                'roling1_norma' => 0.4,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 4.800000000000001,
                'roling2_norma' => 0.45,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 5.4,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Pemupukan - Manual',
                'datar_norma' => 1.2008027306726605,
                'datar_rotasi' => 2,
                'datar_nxr' => 2.401605461345321,
                'roling1_norma' => 1.3342252563029562,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 2.6684505126059124,
                'roling2_norma' => 1.4676477819332518,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 2.9352955638665037,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Pemupukan - Mekanis',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Tkks - Manual',
                'datar_norma' => 8,
                'datar_rotasi' => 1,
                'datar_nxr' => 8,
                'roling1_norma' => 9,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 9,
                'roling2_norma' => 10,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 10,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Tkks - Mekanis WK',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Tkks - Mekanis GB',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Tkks - Mekanis QT',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Rawat Infrastruktur Dalam Blok',
                'datar_norma' => 0.03320161428950716,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0.036521775718457876,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0.039841937147408586,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Sensus Produksi',
                'datar_norma' => 0.0333,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.09990000000000002,
                'roling1_norma' => 0.03663000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.10989000000000003,
                'roling2_norma' => 0.03996,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.11988000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Sensus Jumlah Pokok',
                'datar_norma' => 0.2,
                'datar_rotasi' => 0.5,
                'datar_nxr' => 0.1,
                'roling1_norma' => 0.2,
                'roling1_rotasi' => 0.5,
                'roling1_nxr' => 0.1,
                'roling2_norma' => 0.2,
                'roling2_rotasi' => 0.5,
                'roling2_nxr' => 0.1,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'Rawat HPT',
                'datar_norma' => 0.12,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.48,
                'roling1_norma' => 0.132,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.528,
                'roling2_norma' => 0.144,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.576,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'LSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM-1',
                'item_kerja' => 'SSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'CW - Manual',
                'datar_norma' => 1.8,
                'datar_rotasi' => 1,
                'datar_nxr' => 1.8,
                'roling1_norma' => 2,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 2,
                'roling2_norma' => 2.2,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 2.2,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'CW - Chemist',
                'datar_norma' => 0.35,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.0499999999999998,
                'roling1_norma' => 0.35,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 1.0499999999999998,
                'roling2_norma' => 0.35,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 1.0499999999999998,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Rawat Path - Chemist',
                'datar_norma' => 0.0675,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.27,
                'roling1_norma' => 0.075,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.3,
                'roling2_norma' => 0.0825,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.33,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Rawat TPH - Chemist',
                'datar_norma' => 0.06213275762092268,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.2485310304836907,
                'roling1_norma' => 0.06834603338301495,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.2733841335320598,
                'roling2_norma' => 0.07455930914510721,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.29823723658042883,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Weeding (Dak) - Manual',
                'datar_norma' => 1.35,
                'datar_rotasi' => 1,
                'datar_nxr' => 1.35,
                'roling1_norma' => 1.45,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 1.45,
                'roling2_norma' => 1.6,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 1.6,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Weeding - Chemist',
                'datar_norma' => 0.45,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.35,
                'roling1_norma' => 0.45,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 1.35,
                'roling2_norma' => 0.45,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 1.35,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Wipping Lalang',
                'datar_norma' => 0.09000000000000001,
                'datar_rotasi' => 6,
                'datar_nxr' => 0.54,
                'roling1_norma' => 0.09900000000000002,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 0.5940000000000001,
                'roling2_norma' => 0.10800000000000001,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 0.6480000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Rawat/Cuci Flatbat',
                'datar_norma' => 0.20700000000000002,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.41400000000000003,
                'roling1_norma' => 0.22770000000000004,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.4554000000000001,
                'roling2_norma' => 0.2484,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.4968,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Pengaliran Land Aplikasi',
                'datar_norma' => 0.63,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.8900000000000001,
                'roling1_norma' => 0.6930000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 2.079,
                'roling2_norma' => 0.756,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 2.268,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Pruning',
                'datar_norma' => 0.3,
                'datar_rotasi' => 12,
                'datar_nxr' => 3.5999999999999996,
                'roling1_norma' => 0.35,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 4.199999999999999,
                'roling2_norma' => 0.35,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 4.199999999999999,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Pemupukan - Manual',
                'datar_norma' => 1.2008027306726605,
                'datar_rotasi' => 2,
                'datar_nxr' => 2.401605461345321,
                'roling1_norma' => 1.3342252563029562,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 2.6684505126059124,
                'roling2_norma' => 1.4676477819332518,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 2.9352955638665037,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Pemupukan - Mekanis',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Tkks - Manual',
                'datar_norma' => 8,
                'datar_rotasi' => 1,
                'datar_nxr' => 8,
                'roling1_norma' => 9,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 9,
                'roling2_norma' => 10,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 10,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Tkks - Mekanis WK',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Tkks - Mekanis GB',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Tkks - Mekanis QT',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Rawat Infrastruktur Dalam Blok',
                'datar_norma' => 0.03320161428950716,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0.036521775718457876,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0.039841937147408586,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Sensus Produksi',
                'datar_norma' => 0.0333,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.09990000000000002,
                'roling1_norma' => 0.03663000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.10989000000000003,
                'roling2_norma' => 0.03996,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.11988000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Sensus Jumlah Pokok',
                'datar_norma' => 0.2,
                'datar_rotasi' => 0.5,
                'datar_nxr' => 0.1,
                'roling1_norma' => 0.2,
                'roling1_rotasi' => 0.5,
                'roling1_nxr' => 0.1,
                'roling2_norma' => 0.2,
                'roling2_rotasi' => 0.5,
                'roling2_nxr' => 0.1,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'Rawat HPT',
                'datar_norma' => 0.12,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.48,
                'roling1_norma' => 0.132,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.528,
                'roling2_norma' => 0.144,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.576,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'LSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM-2',
                'item_kerja' => 'SSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'CW - Manual',
                'datar_norma' => 1.75,
                'datar_rotasi' => 1,
                'datar_nxr' => 1.75,
                'roling1_norma' => 1.95,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 1.95,
                'roling2_norma' => 2.15,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 2.15,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'CW - Chemist',
                'datar_norma' => 0.3,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.6,
                'roling1_norma' => 0.3,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.6,
                'roling2_norma' => 0.3,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.8999999999999999,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Rawat Path - Chemist',
                'datar_norma' => 0.0675,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.2025,
                'roling1_norma' => 0.075,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.22499999999999998,
                'roling2_norma' => 0.0825,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.2475,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Rawat TPH - Chemist',
                'datar_norma' => 0.04555287146538843,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.13665861439616528,
                'roling1_norma' => 0.05010815861192728,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.15032447583578185,
                'roling2_norma' => 0.054663445758466114,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.16399033727539836,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Weeding (Dak) - Manual',
                'datar_norma' => 1.3,
                'datar_rotasi' => 1,
                'datar_nxr' => 1.3,
                'roling1_norma' => 1.4,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 1.4,
                'roling2_norma' => 1.5,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 1.5,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Weeding - Chemist',
                'datar_norma' => 0.33,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.66,
                'roling1_norma' => 0.33,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.66,
                'roling2_norma' => 0.33,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.66,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Wipping Lalang',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Rawat/Cuci Flatbat',
                'datar_norma' => 0.20700000000000002,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.41400000000000003,
                'roling1_norma' => 0.22770000000000004,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.4554000000000001,
                'roling2_norma' => 0.2484,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.4968,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Pengaliran Land Aplikasi',
                'datar_norma' => 0.63,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.8900000000000001,
                'roling1_norma' => 0.6930000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 2.079,
                'roling2_norma' => 0.756,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 2.268,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Pruning',
                'datar_norma' => 0.3,
                'datar_rotasi' => 12,
                'datar_nxr' => 3.5999999999999996,
                'roling1_norma' => 0.3,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 3.5999999999999996,
                'roling2_norma' => 0.35,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 4.199999999999999,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Pemupukan - Manual',
                'datar_norma' => 1.2163140659736222,
                'datar_rotasi' => 2,
                'datar_nxr' => 2.4326281319472445,
                'roling1_norma' => 1.3514600733040247,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 2.7029201466080495,
                'roling2_norma' => 1.4866060806344275,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 2.973212161268855,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Pemupukan - Mekanis',
                'datar_norma' => 0.46317546742642596,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.9263509348528519,
                'roling1_norma' => 0.46317546742642596,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.9263509348528519,
                'roling2_norma' => 0.46317546742642596,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.9263509348528519,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Tkks - Manual',
                'datar_norma' => 8,
                'datar_rotasi' => 1,
                'datar_nxr' => 8,
                'roling1_norma' => 9,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 9,
                'roling2_norma' => 10,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 10,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Tkks - Mekanis WK',
                'datar_norma' => 6.25,
                'datar_rotasi' => 1,
                'datar_nxr' => 6.25,
                'roling1_norma' => 6.25,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 6.25,
                'roling2_norma' => 6.25,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 6.25,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Tkks - Mekanis GB',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Tkks - Mekanis QT',
                'datar_norma' => 5.5,
                'datar_rotasi' => 1,
                'datar_nxr' => 5.5,
                'roling1_norma' => 5.5,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 5.5,
                'roling2_norma' => 5.5,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 5.5,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Rawat Infrastruktur Dalam Blok',
                'datar_norma' => 0.06300000000000001,
                'datar_rotasi' => 12,
                'datar_nxr' => 0.7560000000000002,
                'roling1_norma' => 0.06930000000000003,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 0.8316000000000003,
                'roling2_norma' => 0.07560000000000001,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 0.9072000000000002,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Sensus Produksi',
                'datar_norma' => 0.0333,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.09990000000000002,
                'roling1_norma' => 0.03663000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.10989000000000003,
                'roling2_norma' => 0.03996,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.11988000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Sensus Jumlah Pokok',
                'datar_norma' => 0.2,
                'datar_rotasi' => 0.5,
                'datar_nxr' => 0.1,
                'roling1_norma' => 0.2,
                'roling1_rotasi' => 0.5,
                'roling1_nxr' => 0.1,
                'roling2_norma' => 0.2,
                'roling2_rotasi' => 0.5,
                'roling2_nxr' => 0.1,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'Rawat HPT',
                'datar_norma' => 0.12,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.48,
                'roling1_norma' => 0.132,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.528,
                'roling2_norma' => 0.144,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.576,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'LSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM3-5',
                'item_kerja' => 'SSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'CW - Manual',
                'datar_norma' => 1.75,
                'datar_rotasi' => 1,
                'datar_nxr' => 1.75,
                'roling1_norma' => 1.95,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 1.95,
                'roling2_norma' => 2.15,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 2.15,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'CW - Chemist',
                'datar_norma' => 0.25,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.5,
                'roling1_norma' => 0.25,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.5,
                'roling2_norma' => 0.25,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.75,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Rawat Path - Chemist',
                'datar_norma' => 0.0675,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.2025,
                'roling1_norma' => 0.075,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.22499999999999998,
                'roling2_norma' => 0.0825,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.2475,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Rawat TPH - Chemist',
                'datar_norma' => 0.046086770915646925,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.13826031274694078,
                'roling1_norma' => 0.050695448007211624,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.15208634402163487,
                'roling2_norma' => 0.05530412509877631,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.16591237529632893,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Weeding (Dak) - Manual',
                'datar_norma' => 0.7,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.7,
                'roling1_norma' => 0.75,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.75,
                'roling2_norma' => 0.8,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.8,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Weeding - Chemist',
                'datar_norma' => 0.3,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.6,
                'roling1_norma' => 0.3,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.6,
                'roling2_norma' => 0.3,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.6,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Wipping Lalang',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Rawat/Cuci Flatbat',
                'datar_norma' => 0.20700000000000002,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.41400000000000003,
                'roling1_norma' => 0.22770000000000004,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.4554000000000001,
                'roling2_norma' => 0.2484,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.4968,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Pengaliran Land Aplikasi',
                'datar_norma' => 0.63,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.8900000000000001,
                'roling1_norma' => 0.6930000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 2.079,
                'roling2_norma' => 0.756,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 2.268,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Pruning',
                'datar_norma' => 0.3,
                'datar_rotasi' => 12,
                'datar_nxr' => 3.5999999999999996,
                'roling1_norma' => 0.3,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 3.5999999999999996,
                'roling2_norma' => 0.35,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 4.199999999999999,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Pemupukan - Manual',
                'datar_norma' => 1.1918269007248765,
                'datar_rotasi' => 2,
                'datar_nxr' => 2.383653801449753,
                'roling1_norma' => 1.3242521119165294,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 2.6485042238330587,
                'roling2_norma' => 1.4566773231081824,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 2.913354646216365,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Pemupukan - Mekanis',
                'datar_norma' => 0.4085347240096014,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.8170694480192028,
                'roling1_norma' => 0.4085347240096014,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.8170694480192028,
                'roling2_norma' => 0.4085347240096014,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.8170694480192028,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Tkks - Manual',
                'datar_norma' => 8,
                'datar_rotasi' => 1,
                'datar_nxr' => 8,
                'roling1_norma' => 9,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 9,
                'roling2_norma' => 10,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 10,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Tkks - Mekanis WK',
                'datar_norma' => 6.25,
                'datar_rotasi' => 1,
                'datar_nxr' => 6.25,
                'roling1_norma' => 6.25,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 6.25,
                'roling2_norma' => 6.25,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 6.25,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Tkks - Mekanis GB',
                'datar_norma' => 3,
                'datar_rotasi' => 1,
                'datar_nxr' => 3,
                'roling1_norma' => 3,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 3,
                'roling2_norma' => 3,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 3,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Tkks - Mekanis QT',
                'datar_norma' => 5.5,
                'datar_rotasi' => 1,
                'datar_nxr' => 5.5,
                'roling1_norma' => 5.5,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 5.5,
                'roling2_norma' => 5.5,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 5.5,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Rawat Infrastruktur Dalam Blok',
                'datar_norma' => 0.06300000000000001,
                'datar_rotasi' => 12,
                'datar_nxr' => 0.7560000000000002,
                'roling1_norma' => 0.06930000000000003,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 0.8316000000000003,
                'roling2_norma' => 0.07560000000000001,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 0.9072000000000002,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Sensus Produksi',
                'datar_norma' => 0.0333,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.09990000000000002,
                'roling1_norma' => 0.03663000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.10989000000000003,
                'roling2_norma' => 0.03996,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.11988000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Sensus Jumlah Pokok',
                'datar_norma' => 0.2,
                'datar_rotasi' => 0.5,
                'datar_nxr' => 0.1,
                'roling1_norma' => 0.2,
                'roling1_rotasi' => 0.5,
                'roling1_nxr' => 0.1,
                'roling2_norma' => 0.2,
                'roling2_rotasi' => 0.5,
                'roling2_nxr' => 0.1,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'Rawat HPT',
                'datar_norma' => 0.12,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.48,
                'roling1_norma' => 0.132,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.528,
                'roling2_norma' => 0.144,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.576,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'LSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM6-10',
                'item_kerja' => 'SSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'CW - Manual',
                'datar_norma' => 1.75,
                'datar_rotasi' => 1,
                'datar_nxr' => 1.75,
                'roling1_norma' => 1.95,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 1.95,
                'roling2_norma' => 2.15,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 2.15,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'CW - Chemist',
                'datar_norma' => 0.25,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.5,
                'roling1_norma' => 0.25,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.5,
                'roling2_norma' => 0.25,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.75,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Rawat Path - Chemist',
                'datar_norma' => 0.0675,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.2025,
                'roling1_norma' => 0.075,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.22499999999999998,
                'roling2_norma' => 0.0825,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.2475,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Rawat TPH - Chemist',
                'datar_norma' => 0.046086770915646925,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.13826031274694078,
                'roling1_norma' => 0.050695448007211624,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.15208634402163487,
                'roling2_norma' => 0.05530412509877631,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.16591237529632893,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Weeding (Dak) - Manual',
                'datar_norma' => 0.7,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.7,
                'roling1_norma' => 0.75,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.75,
                'roling2_norma' => 0.8,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.8,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Weeding - Chemist',
                'datar_norma' => 0.26,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.52,
                'roling1_norma' => 0.26,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.52,
                'roling2_norma' => 0.26,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.52,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Wipping Lalang',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Rawat/Cuci Flatbat',
                'datar_norma' => 0.20700000000000002,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.41400000000000003,
                'roling1_norma' => 0.22770000000000004,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.4554000000000001,
                'roling2_norma' => 0.2484,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.4968,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Pengaliran Land Aplikasi',
                'datar_norma' => 0.63,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.8900000000000001,
                'roling1_norma' => 0.6930000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 2.079,
                'roling2_norma' => 0.756,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 2.268,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Pruning',
                'datar_norma' => 0.33,
                'datar_rotasi' => 12,
                'datar_nxr' => 3.96,
                'roling1_norma' => 0.4,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 4.800000000000001,
                'roling2_norma' => 0.4,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 4.800000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Pemupukan - Manual',
                'datar_norma' => 1.1918269007248739,
                'datar_rotasi' => 2,
                'datar_nxr' => 2.3836538014497477,
                'roling1_norma' => 1.3242521119165294,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 2.6485042238330587,
                'roling2_norma' => 1.4566773231081824,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 2.913354646216365,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Pemupukan - Mekanis',
                'datar_norma' => 0.4085347240096014,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.8170694480192028,
                'roling1_norma' => 0.4085347240096014,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.8170694480192028,
                'roling2_norma' => 0.4085347240096014,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.8170694480192028,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Tkks - Manual',
                'datar_norma' => 8,
                'datar_rotasi' => 1,
                'datar_nxr' => 8,
                'roling1_norma' => 9,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 9,
                'roling2_norma' => 10,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 10,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Tkks - Mekanis WK',
                'datar_norma' => 6.25,
                'datar_rotasi' => 1,
                'datar_nxr' => 6.25,
                'roling1_norma' => 6.25,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 6.25,
                'roling2_norma' => 6.25,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 6.25,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Tkks - Mekanis GB',
                'datar_norma' => 3,
                'datar_rotasi' => 1,
                'datar_nxr' => 3,
                'roling1_norma' => 3,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 3,
                'roling2_norma' => 3,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 3,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Tkks - Mekanis QT',
                'datar_norma' => 5.5,
                'datar_rotasi' => 1,
                'datar_nxr' => 5.5,
                'roling1_norma' => 5.5,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 5.5,
                'roling2_norma' => 5.5,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 5.5,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Rawat Infrastruktur Dalam Blok',
                'datar_norma' => 0.06300000000000001,
                'datar_rotasi' => 12,
                'datar_nxr' => 0.7560000000000002,
                'roling1_norma' => 0.06930000000000003,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 0.8316000000000003,
                'roling2_norma' => 0.07560000000000001,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 0.9072000000000002,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Sensus Produksi',
                'datar_norma' => 0.0333,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.09990000000000002,
                'roling1_norma' => 0.03663000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.10989000000000003,
                'roling2_norma' => 0.03996,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.11988000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Sensus Jumlah Pokok',
                'datar_norma' => 0.2,
                'datar_rotasi' => 0.5,
                'datar_nxr' => 0.1,
                'roling1_norma' => 0.2,
                'roling1_rotasi' => 0.5,
                'roling1_nxr' => 0.1,
                'roling2_norma' => 0.2,
                'roling2_rotasi' => 0.5,
                'roling2_nxr' => 0.1,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'Rawat HPT',
                'datar_norma' => 0.12,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.48,
                'roling1_norma' => 0.132,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.528,
                'roling2_norma' => 0.144,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.576,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'LSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM11-17',
                'item_kerja' => 'SSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'CW - Manual',
                'datar_norma' => 1.8,
                'datar_rotasi' => 1,
                'datar_nxr' => 1.8,
                'roling1_norma' => 2,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 2,
                'roling2_norma' => 2.2,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 2.2,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'CW - Chemist',
                'datar_norma' => 0.2,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.4,
                'roling1_norma' => 0.2,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.4,
                'roling2_norma' => 0.2,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.6000000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Rawat Path - Chemist',
                'datar_norma' => 0.0675,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.2025,
                'roling1_norma' => 0.075,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.22499999999999998,
                'roling2_norma' => 0.0825,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.2475,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Rawat TPH - Chemist',
                'datar_norma' => 0.03741011513440841,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.11223034540322523,
                'roling1_norma' => 0.04115112664784925,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.12345337994354774,
                'roling2_norma' => 0.04489213816129009,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.13467641448387027,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Weeding (Dak) - Manual',
                'datar_norma' => 0.5,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.5,
                'roling1_norma' => 0.55,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.55,
                'roling2_norma' => 0.6,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.6,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Weeding - Chemist',
                'datar_norma' => 0.26,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.52,
                'roling1_norma' => 0.26,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.52,
                'roling2_norma' => 0.26,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.52,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Wipping Lalang',
                'datar_norma' => 0,
                'datar_rotasi' => 0,
                'datar_nxr' => 0,
                'roling1_norma' => 0,
                'roling1_rotasi' => 0,
                'roling1_nxr' => 0,
                'roling2_norma' => 0,
                'roling2_rotasi' => 0,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Rawat/Cuci Flatbat',
                'datar_norma' => 0.20700000000000002,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.41400000000000003,
                'roling1_norma' => 0.22770000000000004,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.4554000000000001,
                'roling2_norma' => 0.2484,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.4968,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Pengaliran Land Aplikasi',
                'datar_norma' => 0.63,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.8900000000000001,
                'roling1_norma' => 0.6930000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 2.079,
                'roling2_norma' => 0.756,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 2.268,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Pruning',
                'datar_norma' => 0.33,
                'datar_rotasi' => 12,
                'datar_nxr' => 3.96,
                'roling1_norma' => 0.4,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 4.800000000000001,
                'roling2_norma' => 0.4,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 4.800000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Pemupukan - Manual',
                'datar_norma' => 1.1818207763259037,
                'datar_rotasi' => 2,
                'datar_nxr' => 2.3636415526518073,
                'roling1_norma' => 1.3131341959176708,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 2.6262683918353416,
                'roling2_norma' => 1.444447615509438,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 2.888895231018876,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Pemupukan - Mekanis',
                'datar_norma' => 0.41197141829744327,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.8239428365948865,
                'roling1_norma' => 0.41197141829744327,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.8239428365948865,
                'roling2_norma' => 0.41197141829744327,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.8239428365948865,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Tkks - Manual',
                'datar_norma' => 8,
                'datar_rotasi' => 1,
                'datar_nxr' => 8,
                'roling1_norma' => 9,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 9,
                'roling2_norma' => 10,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 10,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Tkks - Mekanis WK',
                'datar_norma' => 6.25,
                'datar_rotasi' => 1,
                'datar_nxr' => 6.25,
                'roling1_norma' => 6.25,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 6.25,
                'roling2_norma' => 6.25,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 6.25,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Tkks - Mekanis GB',
                'datar_norma' => 3,
                'datar_rotasi' => 1,
                'datar_nxr' => 3,
                'roling1_norma' => 3,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 3,
                'roling2_norma' => 3,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 3,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Tkks - Mekanis QT',
                'datar_norma' => 5.5,
                'datar_rotasi' => 1,
                'datar_nxr' => 5.5,
                'roling1_norma' => 5.5,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 5.5,
                'roling2_norma' => 5.5,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 5.5,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Rawat Infrastruktur Dalam Blok',
                'datar_norma' => 0.06300000000000001,
                'datar_rotasi' => 12,
                'datar_nxr' => 0.7560000000000002,
                'roling1_norma' => 0.06930000000000003,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 0.8316000000000003,
                'roling2_norma' => 0.07560000000000001,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 0.9072000000000002,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Sensus Produksi',
                'datar_norma' => 0.0333,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.09990000000000002,
                'roling1_norma' => 0.03663000000000001,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.10989000000000003,
                'roling2_norma' => 0.03996,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.11988000000000001,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Sensus Jumlah Pokok',
                'datar_norma' => 0.2,
                'datar_rotasi' => 0.5,
                'datar_nxr' => 0.1,
                'roling1_norma' => 0.2,
                'roling1_rotasi' => 0.5,
                'roling1_nxr' => 0.1,
                'roling2_norma' => 0.2,
                'roling2_rotasi' => 0.5,
                'roling2_nxr' => 0.1,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'Rawat HPT',
                'datar_norma' => 0.12,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.48,
                'roling1_norma' => 0.132,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.528,
                'roling2_norma' => 0.144,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.576,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'LSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TM TUA',
                'item_kerja' => 'SSU',
                'datar_norma' => 0.05,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.05,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.05,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.05,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'CW - Manual',
                'datar_norma' => 1.19,
                'datar_rotasi' => 7,
                'datar_nxr' => 8.33,
                'roling1_norma' => 1.31,
                'roling1_rotasi' => 7,
                'roling1_nxr' => 9.17,
                'roling2_norma' => 1.44,
                'roling2_rotasi' => 7,
                'roling2_nxr' => 10.08,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Weeding - Manual',
                'datar_norma' => 0.45,
                'datar_rotasi' => 6,
                'datar_nxr' => 2.7,
                'roling1_norma' => 0.5,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 3,
                'roling2_norma' => 0.55,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 3.3000000000000003,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Path chemist',
                'datar_norma' => 0.3,
                'datar_rotasi' => 6,
                'datar_nxr' => 1.7999999999999998,
                'roling1_norma' => 0.33,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 1.98,
                'roling2_norma' => 0.33,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 1.98,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Pasar seribu chemist',
                'datar_norma' => 0.01,
                'datar_rotasi' => 6,
                'datar_nxr' => 0.06,
                'roling1_norma' => 0.01,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 0.06,
                'roling2_norma' => 0.01,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 0.06,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'TPH Chemist',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Sisip Palma',
                'datar_norma' => 0.6,
                'datar_rotasi' => 2,
                'datar_nxr' => 1.2,
                'roling1_norma' => 0.63,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 1.26,
                'roling2_norma' => 0.69,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 1.38,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Sensus Pokok',
                'datar_norma' => 0.21,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.42,
                'roling1_norma' => 0.23,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.46,
                'roling2_norma' => 0.25,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.5,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Konsolidasi',
                'datar_norma' => 0.13,
                'datar_rotasi' => 5,
                'datar_nxr' => 0.65,
                'roling1_norma' => 0.14,
                'roling1_rotasi' => 5,
                'roling1_nxr' => 0.7000000000000001,
                'roling2_norma' => 0.15,
                'roling2_rotasi' => 5,
                'roling2_nxr' => 0.75,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'CW - Chemis',
                'datar_norma' => 0.33,
                'datar_rotasi' => 5,
                'datar_nxr' => 1.6500000000000001,
                'roling1_norma' => 0.34,
                'roling1_rotasi' => 5,
                'roling1_nxr' => 1.7000000000000002,
                'roling2_norma' => 0.36,
                'roling2_rotasi' => 5,
                'roling2_nxr' => 1.7999999999999998,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Wipping Lalang',
                'datar_norma' => 0.1,
                'datar_rotasi' => 9,
                'datar_nxr' => 0.9,
                'roling1_norma' => 0.1,
                'roling1_rotasi' => 9,
                'roling1_nxr' => 0.9,
                'roling2_norma' => 0.12,
                'roling2_rotasi' => 9,
                'roling2_nxr' => 1.08,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Kastrasi',
                'datar_norma' => 0.19,
                'datar_rotasi' => 18,
                'datar_nxr' => 3.42,
                'roling1_norma' => 0.2,
                'roling1_rotasi' => 18,
                'roling1_nxr' => 3.6,
                'roling2_norma' => 0.22,
                'roling2_rotasi' => 18,
                'roling2_nxr' => 3.96,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Pemupukan',
                'datar_norma' => 0.33,
                'datar_rotasi' => 10,
                'datar_nxr' => 3.3000000000000003,
                'roling1_norma' => 0.31,
                'roling1_rotasi' => 10,
                'roling1_nxr' => 3.1,
                'roling2_norma' => 0.4,
                'roling2_rotasi' => 10,
                'roling2_nxr' => 4,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Aplikasi TKKS',
                'datar_norma' => 5,
                'datar_rotasi' => 1,
                'datar_nxr' => 5,
                'roling1_norma' => 5.25,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 5.25,
                'roling2_norma' => 5.75,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 5.75,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Rutin HPT',
                'datar_norma' => 0.25,
                'datar_rotasi' => 4,
                'datar_nxr' => 1,
                'roling1_norma' => 0.25,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 1,
                'roling2_norma' => 0.25,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 1,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Tanam Tanmat ',
                'datar_norma' => 0.08,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.32,
                'roling1_norma' => 0.08,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.32,
                'roling2_norma' => 0.08,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.32,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Rawat Infrastruktur',
                'datar_norma' => 0.06,
                'datar_rotasi' => 12,
                'datar_nxr' => 0.72,
                'roling1_norma' => 0.06,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 0.72,
                'roling2_norma' => 0.07,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 0.8400000000000001,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Pengukuran Pelepah',
                'datar_norma' => 0.04,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.16,
                'roling1_norma' => 0.04,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.16,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.2,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'TPH – Manual',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Sanitasi',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Panen Perdana',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Timbang BJR',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 1',
                'item_kerja' => 'Initial Pruning',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'CW - Manual',
                'datar_norma' => 1.31,
                'datar_rotasi' => 4,
                'datar_nxr' => 5.24,
                'roling1_norma' => 1.58,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 6.32,
                'roling2_norma' => 1.73,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 6.92,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Weeding - Manual',
                'datar_norma' => 0.5,
                'datar_rotasi' => 4,
                'datar_nxr' => 2,
                'roling1_norma' => 0.53,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 2.12,
                'roling2_norma' => 0.58,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 2.32,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Path chemist',
                'datar_norma' => 0.3,
                'datar_rotasi' => 6,
                'datar_nxr' => 1.7999999999999998,
                'roling1_norma' => 0.33,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 1.98,
                'roling2_norma' => 0.36,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 2.16,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Pasar seribu chemist',
                'datar_norma' => 0.01,
                'datar_rotasi' => 6,
                'datar_nxr' => 0.06,
                'roling1_norma' => 0.01,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 0.06,
                'roling2_norma' => 0.01,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 0.06,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'TPH Chemist',
                'datar_norma' => 0.01,
                'datar_rotasi' => 6,
                'datar_nxr' => 0.06,
                'roling1_norma' => 0.01,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 0.06,
                'roling2_norma' => 0.01,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 0.06,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Sisip Palma',
                'datar_norma' => 0.3,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.6,
                'roling1_norma' => 0.32,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.64,
                'roling2_norma' => 0.35,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.7,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Sensus Pokok',
                'datar_norma' => 0.21,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.42,
                'roling1_norma' => 0.23,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.46,
                'roling2_norma' => 0.25,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.5,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Konsolidasi',
                'datar_norma' => 0.13,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.13,
                'roling1_norma' => 0.14,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.14,
                'roling2_norma' => 0.15,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.15,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'CW - Chemis',
                'datar_norma' => 0.5,
                'datar_rotasi' => 6,
                'datar_nxr' => 3,
                'roling1_norma' => 0.53,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 3.18,
                'roling2_norma' => 0.58,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 3.4799999999999995,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Wipping Lalang',
                'datar_norma' => 0.2,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.8,
                'roling1_norma' => 0.19,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.76,
                'roling2_norma' => 0.23,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.92,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Kastrasi',
                'datar_norma' => 0.19,
                'datar_rotasi' => 18,
                'datar_nxr' => 3.42,
                'roling1_norma' => 0.19,
                'roling1_rotasi' => 18,
                'roling1_nxr' => 3.42,
                'roling2_norma' => 0.22,
                'roling2_rotasi' => 18,
                'roling2_nxr' => 3.96,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Pemupukan',
                'datar_norma' => 0.33,
                'datar_rotasi' => 12,
                'datar_nxr' => 3.96,
                'roling1_norma' => 0.35,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 4.199999999999999,
                'roling2_norma' => 0.4,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 4.800000000000001,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Aplikasi TKKS',
                'datar_norma' => 8,
                'datar_rotasi' => 1,
                'datar_nxr' => 8,
                'roling1_norma' => 8.4,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 8.4,
                'roling2_norma' => 8.82,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 8.82,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Rutin HPT',
                'datar_norma' => 0.15,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.6,
                'roling1_norma' => 0.15,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.6,
                'roling2_norma' => 0.15,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.6,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Tanam Tanmat ',
                'datar_norma' => 0.08,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.32,
                'roling1_norma' => 0.08,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.32,
                'roling2_norma' => 0.08,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.32,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Rawat Infrastruktur',
                'datar_norma' => 0.06,
                'datar_rotasi' => 12,
                'datar_nxr' => 0.72,
                'roling1_norma' => 0.06,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 0.72,
                'roling2_norma' => 0.07,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 0.8400000000000001,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Pengukuran Pelepah',
                'datar_norma' => 0.05,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.15000000000000002,
                'roling1_norma' => 0.06,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.18,
                'roling2_norma' => 0.06,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.18,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'TPH – Manual',
                'datar_norma' => 0.35,
                'datar_rotasi' => 1,
                'datar_nxr' => 0.35,
                'roling1_norma' => 0.37,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 0.37,
                'roling2_norma' => 0.4,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 0.4,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Sanitasi',
                'datar_norma' => 2,
                'datar_rotasi' => 1,
                'datar_nxr' => 2,
                'roling1_norma' => 2,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 2,
                'roling2_norma' => 2.3,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 2.3,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Panen Perdana',
                'datar_norma' => 0.33,
                'datar_rotasi' => 36,
                'datar_nxr' => 11.88,
                'roling1_norma' => 0.33,
                'roling1_rotasi' => 36,
                'roling1_nxr' => 11.88,
                'roling2_norma' => 0.33,
                'roling2_rotasi' => 36,
                'roling2_nxr' => 11.88,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Timbang BJR',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 2',
                'item_kerja' => 'Initial Pruning',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'CW - Manual',
                'datar_norma' => 1.7,
                'datar_rotasi' => 3,
                'datar_nxr' => 5.1,
                'roling1_norma' => 1.79,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 5.37,
                'roling2_norma' => 1.96,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 5.88,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Weeding - Manual',
                'datar_norma' => 0.5,
                'datar_rotasi' => 3,
                'datar_nxr' => 1.5,
                'roling1_norma' => 0.53,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 1.59,
                'roling2_norma' => 0.58,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 1.7399999999999998,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Path chemist',
                'datar_norma' => 0.3,
                'datar_rotasi' => 6,
                'datar_nxr' => 1.7999999999999998,
                'roling1_norma' => 0.33,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 1.98,
                'roling2_norma' => 0.33,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 1.98,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Pasar seribu chemist',
                'datar_norma' => 0.01,
                'datar_rotasi' => 6,
                'datar_nxr' => 0.06,
                'roling1_norma' => 0.01,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 0.06,
                'roling2_norma' => 0.01,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 0.06,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'TPH Chemist',
                'datar_norma' => 0.01,
                'datar_rotasi' => 6,
                'datar_nxr' => 0.06,
                'roling1_norma' => 0.01,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 0.06,
                'roling2_norma' => 0.01,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 0.06,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Sisip Palma',
                'datar_norma' => 0.3,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.6,
                'roling1_norma' => 0.32,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.64,
                'roling2_norma' => 0.35,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.7,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Sensus Pokok',
                'datar_norma' => 0.21,
                'datar_rotasi' => 2,
                'datar_nxr' => 0.42,
                'roling1_norma' => 0.23,
                'roling1_rotasi' => 2,
                'roling1_nxr' => 0.46,
                'roling2_norma' => 0.25,
                'roling2_rotasi' => 2,
                'roling2_nxr' => 0.5,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Konsolidasi',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'CW - Chemis',
                'datar_norma' => 0.5,
                'datar_rotasi' => 6,
                'datar_nxr' => 3,
                'roling1_norma' => 0.53,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 3.18,
                'roling2_norma' => 0.58,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 3.4799999999999995,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Wipping Lalang',
                'datar_norma' => 0.2,
                'datar_rotasi' => 6,
                'datar_nxr' => 1.2000000000000002,
                'roling1_norma' => 0.2,
                'roling1_rotasi' => 6,
                'roling1_nxr' => 1.2000000000000002,
                'roling2_norma' => 0.23,
                'roling2_rotasi' => 6,
                'roling2_nxr' => 1.3800000000000001,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Kastrasi',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Pemupukan',
                'datar_norma' => 0.38,
                'datar_rotasi' => 12,
                'datar_nxr' => 4.5600000000000005,
                'roling1_norma' => 0.44,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 5.28,
                'roling2_norma' => 0.48,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 5.76,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Aplikasi TKKS',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Rutin HPT',
                'datar_norma' => 0.03,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.12,
                'roling1_norma' => 0.03,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.12,
                'roling2_norma' => 0.03,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.12,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Tanam Tanmat ',
                'datar_norma' => 0.05,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.2,
                'roling1_norma' => 0.05,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.2,
                'roling2_norma' => 0.05,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.2,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Rawat Infrastruktur',
                'datar_norma' => 0.06,
                'datar_rotasi' => 12,
                'datar_nxr' => 0.72,
                'roling1_norma' => 0.06,
                'roling1_rotasi' => 12,
                'roling1_nxr' => 0.72,
                'roling2_norma' => 0.07,
                'roling2_rotasi' => 12,
                'roling2_nxr' => 0.8400000000000001,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Pengukuran Pelepah',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'TPH – Manual',
                'datar_norma' => 0.13,
                'datar_rotasi' => 3,
                'datar_nxr' => 0.39,
                'roling1_norma' => 0.14,
                'roling1_rotasi' => 3,
                'roling1_nxr' => 0.42000000000000004,
                'roling2_norma' => 0.15,
                'roling2_rotasi' => 3,
                'roling2_nxr' => 0.44999999999999996,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Sanitasi',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Panen Perdana',
                'datar_norma' => null,
                'datar_rotasi' => null,
                'datar_nxr' => 0,
                'roling1_norma' => null,
                'roling1_rotasi' => null,
                'roling1_nxr' => 0,
                'roling2_norma' => null,
                'roling2_rotasi' => null,
                'roling2_nxr' => 0,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Timbang BJR',
                'datar_norma' => 0.07,
                'datar_rotasi' => 4,
                'datar_nxr' => 0.28,
                'roling1_norma' => 0.07,
                'roling1_rotasi' => 4,
                'roling1_nxr' => 0.28,
                'roling2_norma' => 0.08,
                'roling2_rotasi' => 4,
                'roling2_nxr' => 0.32,
            ],
            [
                'status_umur_tanaman' => 'TBM 3',
                'item_kerja' => 'Initial Pruning',
                'datar_norma' => 2.2,
                'datar_rotasi' => 1,
                'datar_nxr' => 2.2,
                'roling1_norma' => 2.2,
                'roling1_rotasi' => 1,
                'roling1_nxr' => 2.2,
                'roling2_norma' => 2.2,
                'roling2_rotasi' => 1,
                'roling2_nxr' => 2.2,
            ]
        ];

        foreach ($data as $item) {
            NormaKerja::create($item);
        }
    }
}
